server:
  port: 8080

logging:
  level:
    root: INFO

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.90,0.95,0.99
  datadog:
    metrics:
      export:
        apiKey: 2db422a83a4b94289d48ad223c7bf707
        step: 5s
        uri: https://us5.datadoghq.com/
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus